const names = require("./4-name")
const sayHi = require("./5-utils")
const data=require("./6-alternativeexport.js") 
console.log(names)
require('./7-removeconsolelog')
console.log(data)
sayHi(`susan`)
sayHi(names.john)
sayHi(names.peter)
